### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/animal-rescue-website#1]
https://docs.google.com/spreadsheets/d/1P_fXIUF-v1CFSmdzCWUiyEHcMtnem6OlGARlYP13WVo/edit?usp=sharing

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
