### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by AveryDion** [AveryDion/animal-rescue-website#2]
Some things that I struggled with when making this website was compressing images and creating mobile navigation. When compressing the images, I had issues with not making the files small enough and the images being different sizes. In the end, I made sure all the images that I wanted to look the same were the same size, and I had to drop the quality pretty low in the save for web menu. As for the mobile navigation I was having problems moving the checkbox off the screen. I copied the code from a previous project where it worked fine, however it wasn’t working for this assignment. Eventually, I just push the mobile navigation to be right at the top because that was the only way I could find to hide the checkbox.

I applied this term's material in many ways. I used what we learned about compressing images to format my images using the save for web feature in Illustrator and Photoshop. I also used imageOptim and Spritebot to compress my jpegs and svgs. I applied transitions to the hover on the buttons on my website using what was taught in class. I also used icons for the logo and on my homepage as an element of the info cards. Another thing we learned that I used was accessibility. I made sure my website used skip links, aria labels, and other necessities for accessibility like colour contrast.

I would give myself an A-. I did a pretty good job, if I spent more time on this project instead of my final assignments for other classes I think it would have turned out better. I also could have used more of what we learned this semester like animations, but I didn’t see anywhere I could put an animation in that would make sense. I also could have spent more time improving the layout, fonts, and colours but I think it looks okay as is. Overall the website works pretty well, there are just a few problems with how things line.

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`
